apiVersion: v1
kind: Pod
metadata:
  name: sim-pod
  namespace: default
  labels:
    app: attack-sim
  annotations:
    container.apparmor.security.beta.kubernetes.io/attack-sim: unconfined
spec:
  containers:
  - name: attack-sim
    image: attack-sim:latest
    imagePullPolicy: Never # Use local image
    securityContext:
      privileged: true
      runAsUser: 0
      capabilities:
        add: ["ALL"]
      seccompProfile:
        type: Unconfined
    env:
    - name: PAYLOAD_SERVER
      value: "payload-server.default.svc.cluster.local"
    - name: PAYLOAD_SERVER_PORT
      value: "8080"
    volumeMounts:
    - name: docker-sock
      mountPath: /var/run/docker.sock
    - name: host-fs
      mountPath: /host
  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
  - name: host-fs
    hostPath:
      path: /